remove unnecessary sweep guard
porter-finance/v1-core pull request #176
Opened 2022-03-31 21:21 UTC by RusseII

Can we remove this? As far as I understand, the contract should never have custody of bond tokens. If a user accidentally sends the bond tokens to the bond contract I believe they should be able to be retrieved using sweep. 

LMK if I'm missing something @Namaskar-1F64F

2022-03-31 21:44 UTC, Namaskar-1F64F commented
does the test not fail? `should disallow removal of tokens: collateral, payment, or itself`

2022-03-31 21:45 UTC, Namaskar-1F64F requested changes
remove test case

2022-03-31 21:45 UTC, RusseII commented
> 
does the test not fail? should disallow removal of tokens: collateral, payment, or itself

It does - I wanted to get your thoughts before adding the tests

2022-03-31 22:15 UTC, Namaskar-1F64F commented
OK. can you make it a draft PR in the future when it's not ready to merge?

2022-04-01 16:44 UTC, Namaskar-1F64F approved these changes

2022-04-01 16:44 UTC, merged