allow preview for payment amount
porter-finance/v1-core pull request #242
Opened 2022-04-13 15:00 UTC by RusseII

# Problem 
There is currently not a good way for a user to know much collateral with be unlocked from a payment. An issuer may wonder "if i pay 10000, how much collateral will I be able to withdraw?" 

This adds that functionality to the `previewWithdraw` method. If the user is paying back 10,000 the frontend could call 

```javascript
<> After paying you'll be able to withdraw ${previewWithdraw(10,000)} tokens! </>
```

# Feedback plz 

I'm looking for suggestions for maybe a better way to do this. 

This is how I thought about doing it with the least number of code modifications.

2022-04-13 17:07 UTC, Namaskar-1F64F reviewed
I think this makes sense. The weird part is the preview function accepts a "fake" payment parameter, but then we're using the previewWithdraw inside our "real" withdraw function. I know it's OK because we're passing in `0` for the "real" withdraw function. The only thing I could think of is naming it something different, but don't love any of my ideas. `previewWithdrawWithPayment`, `previewWithdrawAfterPayment`, `previewPayment`, `previewPaymentAndWithdraw`.

2022-04-13 17:27 UTC, RusseII commented
> The only thing I could think of is naming it something different, but don't love any of my ideas. previewWithdrawWithPayment, previewWithdrawAfterPayment, previewPayment, previewPaymentAndWithdraw

Same... I didn't really like any of those ideas either. Maybe @Pet3ris will have a good idea when he does a full code review :)

2022-04-13 18:09 UTC, Namaskar-1F64F requested changes

2022-04-13 18:32 UTC, merged

2022-04-14 16:49 UTC, Pet3ris commented
Could you use the ERC4626 style pure function `convertPaymentToCollateral(uint256 paymentAmount) returns (uint256 collateralAmount)` ?